"""add migration

Revision ID: 19e4f703f9bb
Revises: None
Create Date: 2021-01-15 09:01:05.010475

"""

# revision identifiers, used by Alembic.
revision = '19e4f703f9bb'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=250), nullable=True),
    sa.Column('forenames', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_watchers',
    sa.Column('filename', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('filename')
    )
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_authors',
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('primary_author', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], )
    )
    op.create_table('paper_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('coresc', sa.String(length=25), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentences')
    op.drop_table('paper_files')
    op.drop_table('paper_authors')
    op.drop_table('papers')
    op.drop_table('paper_watchers')
    op.drop_table('authors')
    # ### end Alembic commands ###
