"""Added doi field to paper table

Revision ID: 24e08f3b6989
Revises: 4abc902af771
Create Date: 2013-05-07 07:57:20.280359

"""

# revision identifiers, used by Alembic.
revision = '24e08f3b6989'
down_revision = '4abc902af771'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('doi', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'doi')
    ### end Alembic commands ###
