"""Added doi field to paper table

Revision ID: 24e08f3b6989
Revises: 4abc902af771
Create Date: 2013-05-07 07:57:20.280359

"""
import logging

# revision identifiers, used by Alembic.
revision = '24e08f3b6989'
down_revision = '4abc902af771'

from alembic import op, context
import sqlalchemy as sa
from sqlalchemy import engine_from_config, pool


from partridge.tools.paperstore import PaperParser
from partridge.models import db
from partridge.models.doc import Paper


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('doi', sa.String(length=50), nullable=True))

    for paper in Paper.query.all():
        
        for file in paper.files:
            if file.path.endswith("_final.xml"):
                
                p = PaperParser()
                p.parsePaper(file.path)

                doi = p.extractDOI()


                if doi != None:
                    doi_lit = op.inline_literal(doi)

                    sql = "UPDATE papers SET doi=%s WHERE id= %s" %(
                        doi_lit,paper.id) 

                    logging.info("Updating doi to %s for paper_id=%s", doi_lit,
                    paper.id)

                    op.execute(sql)
        



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'doi')
    ### end Alembic commands ###
