"""Added type to papers table

Revision ID: 254c397fb9c5
Revises: None
Create Date: 2013-03-05 11:29:42.412130

"""

# revision identifiers, used by Alembic.
revision = '254c397fb9c5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('type', sa.String(length=25), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'type')
    ### end Alembic commands ###
